name: Encode and generate new release for plugin

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

env:
  PLUGIN_NAME: payment-checkout-pagseguro-for-lifterlms

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Executar Plugin Check com configurações personalizadas
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: './'
        exclude-directories: 'node_modules,vendor,.eslintrc'
        ignore-codes: |
          WordPress.WP.I18n.TextDomainMismatch
          WordPress.Security.NonceVerification.Missing
          WordPress.Security.NonceVerification.Recommended
          WordPress.DB.SlowDBQuery.slow_db_query_meta_key
          WordPress.DB.SlowDBQuery.slow_db_query_meta_value
          WordPress.PHP.DevelopmentFunctions.error_log_var_export
          WordPress.WP.EnqueuedResourceParameters.MissingVersion
          WordPress.WP.EnqueuedResourceParameters.NoExplicitVersion
          WordPress.Files.FileName.InvalidClassFileName
          WordPress.Files.FileName.NotHyphenatedLowercase
          trademarked_term
          textdomain_mismatch
          hidden_files
          file_type
          invalid_file_name
          enqueued_resources_in_footer
        categories: |
          performance
          accessibility
          general
          plugin_repo
          security
        strict: true


    - name: Make plugin root directory
      run: "rm -Rf ./includes/plugin-updater && mkdir ${{env.PLUGIN_NAME}} && mv -t ./${{env.PLUGIN_NAME}} ./admin ./includes ./languages ./public *.php LICENSE *.txt && find ./${{env.PLUGIN_NAME}} -type f -exec chmod 0644 {} + && find ./${{env.PLUGIN_NAME}} -type d -exec chmod 0755 {} + && ls -lah"

    # Compact plugin as .zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        path: "${{ env.PLUGIN_NAME }}"
        directory: "."
        filename: "${{ env.PLUGIN_NAME }}.zip"
        exclusions: "*.git* /*node_modules/* .editorconfig"

    # Update version tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: "2.0.5" # TODO alterar em futuras atualizações. 

    # Generate new release
    - name: Generate new Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.PLUGIN_NAME }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: "main"
        draft: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}